# name of the github actions workflow:
name: Publish MkDocs via GitHub Pages
# only run thhis workflow after a new push to the "main" branch:
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      # checkout the contents of the repository
      - uses: actions/checkout@v2
      # set up a python environment:
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      # install all python dependencies (listed in requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      # build docs and deploy to github pages:
      - name: Deploy Files
        run: |
          mkdocs gh-deploy --force
